# Generated by Django 4.2.1 on 2023-12-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120, null=True, unique=True)),
                ('title', models.CharField(max_length=120, null=True)),
                ('blog', models.CharField(max_length=2000, null=True)),
            ],
        ),
    ]
