# Generated by Django 4.2.1 on 2023-12-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='username',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
