# Generated by Django 4.2.1 on 2023-12-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_alter_blog_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
